version: '3.1'

services:

  # BACKEND
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/backend/
    restart: always
    env_file:
      - ./.env.dev

  # DB
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lumberjack
      - POSTGRES_PASSWORD=lumberjack
      - POSTGRES_DB=lumberjack
    env_file:
      - ./.env.dev

#  # CELERY WORKER
#  celery_worker:
#    build: ./backend
#    command: celery -A lumberjack worker --loglevel=INFO
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - backend
#    restart: always
#
#  # CELERY BEAT
#  celery_beat:
#    build: ./backend
#    command: celery -A lumberjack beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
#    env_file:
#      - ./.env.dev
#    depends_on:
#      - backend
#    restart: always

volumes:
  postgres_data:

